version: "3"
services:
  postgres-digi-database:
    image: postgres:9.6
    container_name: "postgres-digi-api"
    environment:
      - POSTGRES_DB=digidatabase
      - POSTGRES_USER=jijimon
      - POSTGRES_PASSWORD=digiworld
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5433:5432