server:
  port: 8080

spring:
  application:
    name: digimon-api
  datasource:
    url: jdbc:postgresql://localhost:5433/digidatabase?autoReconnect=true&useSSL=false
    username: jijimon
    password: digiworld
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: validate
        temp:
          use_jdbc_metadata_defaults: false
  banner:
    immage:
      location: banner.txt

  output:
    ansi:
      enabled: ALWAYS

flyway:
  enabled: true

# Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
# spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false

# Because detection is disabled you have to set correct dialect by hand.
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect