server:
  port: 8080

spring:
  application:
    name: digimon-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?autoReconnect=true&useSSL=false
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: validate
        temp:
          use_jdbc_metadata_defaults: false

flyway:
  enabled: true

# Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
# spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false

# Because detection is disabled you have to set correct dialect by hand.
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect